version: '3.5'

services:

  toupee_touche:
    image: jahrik/toupee_touche:aarch64
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.network=traefik
        - traefik.http.routers.toupee_touche.rule=Host(`toupeetouche.com`)
        - traefik.http.routers.toupee_touche.entrypoints=web,websecure
        - traefik.http.routers.toupee_touche.service=toupee_touche
        - traefik.http.routers.toupee_touche.tls=true
        - traefik.http.services.toupee_touche.loadbalancer.server.port=3000
      placement:
        constraints:
          - node.labels.arch == aarch64

networks:
  traefik:
    name: traefik
    driver: overlay
    external: true
