FROM arm64v8/node:latest

ENV NODE_PORT=3000

WORKDIR /usr/src/app

COPY v2/ .

EXPOSE 3000
CMD [ "npm", "start" ]

# v1
# FROM arm64v8/nginx
# 
# WORKDIR /usr/share/nginx/html
# 
# ADD https://raw.githubusercontent.com/photonstorm/phaser/master/dist/phaser.js phaser.js
# COPY v1/assets ./assets
# COPY v1/index.html ./


